

title: Sallar Kaboli
subtitle:
description: Sallar Kaboli / Exploring JavaScript & Things.
author: Sallar Kaboli
language: English

source: http://sallar.me/

url: https://kiamazi.github.io/miratest/sallaren/
root: /miratest/sallaren/

icon: /miratest/static/theme/sallar/img/logo.png
css: style-ltr.css

static: /miratest/sallaren/static/
imageurl: /miratest/sallaren/img/

## default post permanent link
permalink: :year/:month/:day/:title/

default_markup: markdown

post_num: 10
archive_post_num: 20

template: sallar

lists:
 - tags

disqus_shortname: sallar


