
title: سالار کابلی
subtitle:
description: من سالار کابلی هستم، توسعه‌دهنده نرم‌افزار در کیاسکد. 
author: سالار کابلی
language: Farsi

source: http://sallar.me/farsi/

url: https://kiamazi.github.io/miratest/sallarblog/
root: /miratest/sallarblog/

icon: /miratest/static/theme/sallar/img/logo.png
css: style-rtl.css

static: /miratest/sallarblog/static/
imageurl: /miratest/sallarblog/img/

## default post permanent link
permalink: :year/:month/:day/:title/

default_markup: markdown

post_num: 10
archive_post_num: 20
template: sallar

lists:
 - categories

namespace:

plugins:
 - Jdate

disqus_shortname: sallar


